# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-19 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertreview', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagelink', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientname', models.CharField(blank=True, max_length=120, null=True)),
                ('ingredientvalue', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newslink', models.CharField(blank=True, max_length=120, null=True)),
                ('news', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=120, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('barcode', models.IntegerField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductName')),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videolink', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductName')),
            ],
        ),
        migrations.AddField(
            model_name='productdetail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductName'),
        ),
        migrations.AddField(
            model_name='newsdetail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductName'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductName'),
        ),
        migrations.AddField(
            model_name='imagedetail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductName'),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductName'),
        ),
        migrations.AddField(
            model_name='categorydetail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductName'),
        ),
        migrations.AddField(
            model_name='allergydetail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductName'),
        ),
    ]
