# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-19 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='quantity',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
