# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180819_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat', models.CharField(blank=True, max_length=120, null=True)),
                ('salt', models.CharField(blank=True, max_length=120, null=True)),
                ('protein', models.CharField(blank=True, max_length=120, null=True)),
                ('carbohydrate', models.CharField(blank=True, max_length=120, null=True)),
                ('energy', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductName')),
            ],
        ),
    ]
