# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_nutritionvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionvalues',
            name='other',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionvalues',
            name='carbohydrate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionvalues',
            name='energy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionvalues',
            name='fat',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionvalues',
            name='protein',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionvalues',
            name='salt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
